name: Generate Snake (Windows)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Python (or Node.js if using JavaScript)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # You can replace this with a Python or Node.js script that generates the desired content
      - name: Run snake generation script (Windows version)
        run: python generate_snake.py  # Replace this with your own Windows-compatible script

      - name: Show build status
        run: git status

      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
